import pyperclip

def add_gt_in_front_of_paragraphs(text):
    # Split the text into paragraphs based on double newline
    paragraphs = text.split('\n\n')

    # Add '> ' in front of each paragraph
    updated_paragraphs = [f'> {paragraph.strip()}' for paragraph in paragraphs]

    # Join the paragraphs back with double newline
    updated_text = '\n\n'.join(updated_paragraphs)

    return updated_text

# Sample input text
input_text = """I 23m was repeatedly stuck playing the part of helper and babysitter on family outings. I had to move out of my parents' house because I kept being forced to help watch my three nephews. Last year we took a family vacation in summer to the coast. I rode along with my parents, and they paid for my hotel room. Only, I had to share that room with three rowdy boys because my sister and her husband wanted a room to themselves. I was promised time to do my own things on the vacation. But instead I ended up having to help with these kids. I complained to everyone about it, and was reminded I was there for free. And then we pretty much just did only one thing I wanted to do. Which was tour an art gallery. I like doing this whenever I'm at the coast. But the kids find it boring.

This year my parents have a beach trip planned for June. And they assumed I'd be riding along the same way as last year. But I refused. I said I'd be driving myself, and paying for my own hotel stay to have my own room. My parents were shocked, and tried to remind me of the cost. I said it was no worry. I've got a good job and a decent running car. I can more than afford it. That's when the "Buts" started. I stated the previously listed things as why I'll be driving myself and paying for myself. I want to be able to enjoy this vacation as an adult, and not be treated like a child like last year.

My parents told my sister, and she called to blow up at me that I'll be ruining the vacation if I'm off doing my own thing while she has to wrangle her three boys. I ended up yelling at her that last year all she did was rope me into her mess. I didn't really get to do much of anything I wanted to do. And I was treated like the bad guy for wanting to just go to an art gallery. I'm a grown man. I deserve my own vacation too.

Now my sister is not speaking to me, and my parents are still trying to convince me to just ride with them to keep the peace. I'm still refusing. But the pressure is getting to me. AITA for not giving in? I know they'll have a pretty hard time when they won't have another person there to help.

Edit: It's barely been an hour since I posted. But my sister is apparently a reddit lurker in the mornings, and she saw my post. Not only is she furious with me. But she's also upset no one in the comments is siding with her. To make it short, she went on a big rant about how it's so hard to be a parent to triplets. And the least I could do is help because I'm young and single, and she needs a break. I stood my ground on my decision, and now she's calling our parents to get them involved. I'm expecting a call from them any minute.

Update: Well I'm off work now, so I can tell more of what went down. I guess you could say it's over. My sister got our parents involved, they looked at my post, and were absolutely horrified by the continuous influx of commenters. Yes they're very angry with me that I posted here. But I told them that if they'd just listened to me to begin with, I'd have never needed to. I'm sick of the whole keep the peace mentality that sacrifices me to placate my sister. They in turn went off on my sister, and to make a long story short the whole vacation has been canceled. The hotel wasn't booked yet anyway. But my parents are arguing with my sister, my sister is blaming me, and my nephews are crying because they aren't going to the beach. My sister called me at lunch and basically implied I have no life, which is why I have time to help. I recorded that and told our parents, and that's currently what they're fighting about.

Smol Update: I wasn't gonna update again. But here's a little more. Parents said that they won't ever push babysitting of my nephews on me again, and have agreed that what happened last year was unfair to me. Right now they're VERY angry with my sister for telling me I should help her because she thinks I have no life. My sister is playing the victim. And my brother in law is basically saying "Nope!" to the whole mess and spending most of his time at work.
Thank you to everyone who has commented. You made my day.

OOP is voted NTA

Update Post 1: June 2, 2023 (1 week later)

A week ago I made this throwaway account to ask AITA a question I was found to be anything but TA in. I have too much to say to post in AITA as an update. So a friend recommended I come here. My posting on AITA essentially opened a Pandora's Box in the family. Basically, my parents and older sister had become VERY comfortable with me helping with the childcare of my young triplet nephews. I didn't leave home till I was 22 because I was trying to save money while also going to college. A scholarship covered a lot, and living at home kept me from getting rising debt due to my working part time as well. I'm very thankful for this. However after college everyone just seemed to act like I had endless time on my hands, and convinced me along on a family vacation. In this so-called vacation, I was forced to babysit my three at the time 6 year old nephews. I even had to share a hotel room with them. And believe me, those kids did not listen to a damn thing I said on the first night until I called their mother, TWICE! And I was treated like the bad guy for wanting to do other things during the trip. Like if it's something the family doesn't enjoy as a whole, then it doesn't happen. Which was extremely hypocritical because I'm family and wasn't included in that vote. And you can bet I aired this grievance with my parents after my last post. And they have acknowledged being in the wrong.

After that awful vacation last year, I decided it was time to move out. And did so before the summer even ended. Which surprised everyone as I gave them no warning. I'd landed a great job pretty much right after college thanks to an internship, and used moving as an excuse to drop my commute from 45 minutes, to 15. My sister hated this the most because it meant no more free babysitting on weekends. But she still tried to make me do it. I caved sometimes. Usually by being bribed with pizza. And this sort of became a new norm. But then last month my parents announced plans for another family vacation to the same place along the coast. And they basically wanted it to go the same way. I immediately saw it for what it was. A trap! I knew that if I rode with my parents and let them buy the hotel rooms, I would be screwed over the same way as last time. So I just casually stated I'd drive myself and pay for myself. And that's when the shit-storm started.

When my parents realized they couldn't entrap me like before, they resorted to borderline begging. And my sister practically tried to order me to go with the flow through gaslighting. News-flash, I didn't! After I didn't cave to my sister's demands, I made the AITA post after days of harassment. And then my sister somehow spotted that post in less than an hour. What followed was Pandora's Box. At first the family was against me. My sister called our parents, and they called me when I still had a little time to talk in the morning. My parents were on the phone with me while also reading my post. I asked them if anything in the post was a lie. They sort of steered around it and called the post an exaggeration. But I pointed out numerous details that made it pretty much on the mark. Then I told them to check the comments. There were already far too many to read. I was repeatedly refreshing the page on my home PC and telling them how many comments there were. Then I told them I was sick of their mentality of keeping the peace by forcing me to placate my sister. Then I said I was out of time and we would have to resume this later. Well my parents were positively horrified that hundreds, if not thousands of people were commenting in a matter of hours. And later on I told them that the numbers had basically doubled, and were still growing. Which only added to their horror. So I guess they were forced to take a long look at their own actions.

My sister tried to call me to bitch while I was at work. But my phone was on silent till my lunch break, so all she could do was leave messages and texts. But she was persistent and managed to get through to me when I was eating my lunch. The gist of the conversation was my post had taken our parents away from her side. And now they were mad at her. In the ensuing argument between them, my parents canceled the entire vacation. Yes they later acknowledged they just passed the blame out of embarrassment. And have fully accepted fault. They told me no excuses could excuse the fact they made me their go-to free babysitter when I wasn't even living at home anymore. They did try to backtrack a little by pointing out they never charged me rent while I was in college. But I reminded them kids don't ask to be born, and I was doing my hardest to make my own way. Then I pointed out my father had the same kind of leg up from his parents. They let him live free of charge at home while he was in college. That basically ended any argument my parents had left.

When my sister managed to call me at lunch, I presented the facts to her. And she showed her true colors. She implied that I have no life, and that my free time on weekends should be spent helping her because she is tired and unable to even go out without bringing her children with her unless someone is watching them. She is a stay at home mother with a husband that makes a decent salary. They live in a pretty decent house that's owned, not rented. And to be frank, my nephews aren't really my responsibility. They just forced them on me and expected it to stay that way. My sister angrily hung up on me. But I'd recorded the call and then played it to my parents later. They were furious. And they basically went to war with my sister. My sister dug her heels in, blamed me, and then doubled down on her belief my life should circle around hers. I told her that was the most narcissistic and entitled thing she's ever said about me. It took days, but her husband finally stepped in, and forced her to apologize to me. I'd never seen her cowed like that by anyone. But she was on the verge of crying.

It ended up being admitted that one of the reasons I was the go-to babysitter was because my sister didn't trust strangers. It was never about the money. Or was it? Actually, my brother in law thought my sister was paying me for my time watching her kids after I moved out of my parents' house. She didn't even give me gas money. Just gave me cash that was enough to order pizza for both myself and the kids, and pocketed the rest. My sister had been short-changing me for months. He blew up at her when this came out during her half-assed apology, and she was forced to pay me what she owed me in cash entirely from her own savings, which she looked very sore about. Then my brother in law apologized to me for his own inaction in letting my sister walk all over me, and promised they'd get a normal babysitter from now on. Yes it'll cause a bit of a drop in the bucket for them. But my sister will be getting date nights back. Then came the family meeting the other day's evening. We all gathered up at my parents' house, and everything was laid bare. Apologies all around, and what-not.

Then my parents reinstated the family vacation. And yes, I still plan to drive myself and pay for my own hotel stay. I'll even stay in a completely different hotel if my sister tries to revert me to child care. And I have stated this. She's promised me that won't happen. And if I don't update again after the vacation in another month or so, then you'll all know everything is fine.

Relevant Comment:

Did sis emotionally abuse you when you were growing up?

"She put me down a fair bit when I was a kid. We've got a decent difference in age. But that stopped when she moved out on her own. It didn't really start up again till she had kids. Because once that happened, she set her sights on me as the free help. Yes she did gaslight me if I complained, whined to our parents that I wasn't being helpful enough, and then I'd fight with my parents and her.

Thankfully college forced them all to ease up on me because I was busy with my education and an internship. Unfortunately once I graduated college, my sister took it as a free pass to believe I had endless time on my hands. But now that I've shown my backbone, I won't ever let her walk all over me like that again. And she knows it too because I've said so to her face. I just feel sorry for whatever babysitters she hires, because she's no doubt going to want to look down on them. I stated that to my brother in law, and warned him that I won't hesitate to go on Reddit about it if she does treat them like crap. He was not happy with me, but also admitted he understood my point, and will make sure she does not do that. Things are kinda neutral between us currently."

Update Post 2: June 8, 2023 (6 days later)

Having a family that knows about your Reddit account has it's disadvantages. Yesterday my sister called me after I got off work to ask me if comments are still coming in. She said she cannot bear the negativity of looking at them herself because the comments are all so hurtful towards her. So I was brutally honest. At least ten comments are still coming in daily, and most of them more or less say the same things about her. She started crying and demanding I delete my Reddit posts. But I refused and told her she can cry to anyone she wants. But the posts stay up because they are my assurance she won't try to treat me like crap anymore. After all, she literally felt like my life should revolve around hers, didn't pay me the babysitting money she was supposed to and pocketed it for herself, and forced me to be the constant babysitter on last year's family vacation so I had pretty much no fun the entire time. Is it really any wonder people are having so much hate for her when she treated me like that

Then when I mentioned the posts have already spread to other websites because I was asked a couple of times to let an article be made about my situation. And there are some videos that were read as well. My sister shrieked hearing that and hung up. My parents then called me begging I take the posts down. I've refused, and stated that I only did this because they didn't stick up for me. This would have never happened if they'd told my sister to treat me like an equal and not a servant. I'm not her butler, babysitter, or handyman. I'm her freaking brother, and a grown ass man! Wouldn't they be tired of this crap in my shoes too?

They agreed, but still begged I take the posts down. I refused, and said that I'll keep making more if they don't start sticking up for me more when my sister comes crying to them. Let her clean up her own messes. Because all the enabling of her led to this. I didn't father those kids. I've got a life of my own, a career I'm still new to, and hopefully soon enough a girlfriend as there's someone I want to ask out. I'm moving my life forward, and I won't be held back. They can either step out of my way, or keep trying to enable my sister. But I assured them that the latter would end badly for them. The only way this posting on Reddit will stop, is if the drama stops. I've kept things anonymous, and I've got a right to vent my very valid frustrations.

Well that left my mother crying, my father just went silent, and I said tears don't move me. They know what it'll take to end this, and that's to stop enabling my sister. Well my sister called me again to yell at me that our parents have told her they aren't dealing with this anymore, and to figure it out herself. Oh, and they told her to be nicer to me too. I just pictured her eye twitching as she internally screamed after hearing that. "Be nice to my kid brother? What is this? Do I look it up on Google?". Yeah I was that sarcastic to her. But it left her crying too when I hung up. My brother in law called me later to get my side of the story. He was mad I'm still posting and made his wife cry. But I explained everything to him, and he said he'd have another talk with my sister.

I'm hoping this drama finally ends here. But the family vacation is still on for late June. I've already booked my room and put in for a day off work so we can all leave on a Friday. My room is also not near the ones my parents, sister, BIL and nephews will be using. In fact, it's not even on the same floor. And when we go to the coast, when it's not a family activity, I'm going to go where I want and do what I want. And you can bet I'm gonna tour those art galleries, pig out on local food, and just enjoy being carefree for a change.

Update Post 3: July 3, 2023 (almost a month after last post)

Well the family vacation is over. Some things both good and bad went as expected. Good in that being my parents didn't enable my sister's trying to make me babysit. Oh yes, she did try. But bad in that being my sister did try to find out which room I was in. But that failed and got her in trouble with her husband again.

Firstly, I made sure to tell the hotel in advance that they were not to give out any of my information to anyone who asked except for police, if something needing that were to come to pass. They assured me over the phone they would not tell a soul. Then on the day of the vacation, I left earlier in the morning than the rest of the family. I knew they wouldn't be able to get moving as a group till a least 10:00 AM. So I left at 9:00 AM. Check-in wouldn't be until 1:00 PM. But I wanted to make sure I had a head start. I sent out an FWI group text and was off like a shot to make the three hour drive. My parents were upset because they'd planned a family brunch on the way. But I pointed out I was never made aware of that. So it was canceled in favor of fast food.

Like I planned, I arrived to the hotel early. Too early for check-in. But I told the desk staff I was there to make sure my parents or sister didn't give them my information. They claimed they don't do that. But I told them I know for a fact it still happens sometimes. So I'm covering my ass. When they happen to be dealing with my mother, and my sister, and three potentially crying boys trying to guilt them at the desk, they had better not yield. And I wanted to know if they try anything. They awkwardly promised me no one but me would get access to my room. Then I decided to go out and get something to eat. I came back more than an hour later, and there was my parents' car and my BIL's big SUV.

I went to the desk to check in after making sure the lobby was clear. And it was. Then I asked the clerk if my family had asked about me, and where I was staying in the hotel. Yeah, they did. But the clerk refused to tell them. My sister had apparently tried to push it. But her husband shut her up. I checked in, went to my room, and then called my folks. I didn't mention I knew what they tried with the clerk, and they conveniently didn't mention it either. Then we all met up as a family to go out and tour around. My sister at one point asked me to watch her kids for a moment, to which I replied "Hell no!" because I knew exactly what she was doing. She would pretend to be gone for a moment, and then would be gone for an hour. I called her out, and her husband told her to stop trying to make me watch their kids. What did my sister do? She just started crying on the spot that she needs a break. Her husband scolded her that he's a tired man, but he wasn't complaining.

My mother have me a nasty look, so I went right to her and said that if she tries to even think that I should be watching those kids, I would walk away from this family vacation right now. It's not my job, and I'm sick and tired of her and my sister acting like it is. Well that made my mother start crying too. And then she just started repeating the words "You're right!" over and over again. This is another old tactic of hers. She tries to look pathetic to guilt me. But I just said I am right, and to just let it go, before walking away. Neither my mother or sister tried anything for the rest of the day.

When we got back to the hotel after dinner, my family were all crowding the elevator. But I didn't get in with them. They asked why and I said I'd wait for the next one. My sister glared at me because she knew exactly what I was doing. Then I just sat in the lobby watching youtube on my phone for fifteen minutes, and then took the elevator up. I was on a different floor, and on the other end of the hotel. I had a splendid night, and the next morning we all went out for breakfast. But I made sure they left first. I was the last one out, just like I was the last one in the night before. Breakfast went fine. Then I gave an FWI that I was gonna be doing my own thing for the day. My mother tried to bring up plans to go to the aquarium, and a couple of other places. So I said I'd meet them for those. But the rest of the day was mine until family dinner. They accepted this. And that day went fine too.

Back at the hotel that evening though, my sister caught me leaving my room. She must have been stalking the whole floor looking for me. I went back to my room to chill a bit before dinner because I was tired from walking so much. And my sister was just down the hall when I left my room to meet them for dinner. She tried to corner me and say that I'd ruined the family vacation for her because now it wasn't hardly any different for her than at home since she had to wrangle her kids. I called bull-spit because my parents were helping her a lot. Then told her that I'm sick of this song and dance of being her scape-goat, and it's already over. So leave me the hell alone and get on with your own life. Then I started walking with her yelling "Hey! I'm trying to talk to you!". I told her I didn't give a crap, and was going to dinner. She followed me to the elevator, and we both said nothing to each other.

I didn't stay silent and told my parents and my brother in law that my sister had stalked me to find my room. She was scolded like a child. She had a pity party, I told her to stop milking it and grow up. The old days when she could force her will on me were over. And then I walked out of the lobby and to my car. This time, I was the first one to dinner. When everyone else arrived, my sister looked depressed. But not a damn thing was said about what happened before. And that was just fine with me. My sister refrained from making eye contact with me the entire evening. And this time I didn't give a crap about riding in the elevator with the rest of them. And I told them bluntly that unless it was an emergency, no one is to come knocking on my door. I had a "DO NOT DISTURB!!" sign for a reason.

The final day everything went swimmingly. Neither my sister or mother bothered me at all. They'd fully surrendered at this point. Yes during the whole vacation, I did play with my nephews a bit. I'm not a complete jerk, I didn't stonewall them. I kept up being the fun uncle. Just not the babysitter uncle. The kids didn't even seem to care. They just wanted to play. I even bought each of them one of those little baggies of crystals and polished stones to take home as a souvenir. There was a bit of mild drama between my sister and her husband. But that was just some small disagreements that I didn't bother to pay attention to.

All in all, I'd call the vacation a win because it finally hit home for my mother and sister that the old way they did things involving me is over, and I have my own life.

Update Post 4: July 7, 2023

They really don't know when to let well enough alone. Hey mom, hey sis! I warned you that if you didn't stop, I would go right back to Reddit. And here I am. The short of it is that my mother and sister saw my last POST and freaked out. My sister was stalking my account for days because she knew I'd post. Well what did she expect? That I would just say everybody had a good time. She called me and cried that I made her look like a bad mother. I ended up replying "Well if the glass slipper fits!".

My sister argued with me some more. But I asked her to name anything in the post that was a lie. She tried several times. But I pointed out that every detail was spot on. So what does she do? She calls mommy! Then my mother showed up at my door demanding I delete all the posts. I told her no. And now I have ammunition for one more. I ended up making her leave crying. I spoke with my mother and father over the phone later, and bluntly told then that their enabling of my sister led to the previous family dynamic. I will never go back to how things were. So if they have any hope of that left, I'm snuffing it out for good.

My parents then told my sister for the love of god to stop blaming me and to leave me alone. They can't take the stress of my retaliation anymore. Well my sister had a literal "No one loves me!" pity party. And my parents had to snap her back to reality. My brother in law hasn't called. Pretty sure he's staying indifferent/neutral. But this can't be good for his marriage or my familial connection to him. So out of respect to my brother in law, I am sorry man. But your wife just pushed me too far. Currently my parents are insisting my sister gets counseling. Because she can't be a mom and juggle the habits of her old life too. Woman up as they say.

Either way I'm hoping this is my last post. You hear that sis! If you don't stop thinking I should have been your personal slave, babysitter, watchdog, ETC ETC, and want to keep acting like the whole world is against you because you can't lord over me, then we can't be around each other. Maybe we can get along and move past this crap if you're willing. Don't give me a reason to write anything else and the reddit posts about you end here. I'll only post ones involving me and the treatment I get from people. Treat me like a decent human being, and this will be over. Kapeesh?!

Update: (Editor's note: I unfortunately don't know when this was added to the above post because reveddit, unddit and rareddit don't work anymore. Web archive did not save it nor did google cache.)

My parents and I had a long talk, in which they have apologized. And for the moment we have agreed that I'll keep a bit of a distance until Thanksgiving. I also had a man to man talk with my brother in law last night over some cold beers. He told my sister she needed counseling, or he would separate from her. And they are in the process of finding her a counselor. He also told me that while my sister was an absolute witch to me, at home she is a very loving and endearing wife. But she also admitted that she liked being an only child. We're nearly a decade apart in age, so my sister held onto some resentment about that for a long time, and just let it build up. She's agreed that she does need counseling, and will be going as soon as they get it set up. They've also found a qualified babysitter to look after my nephews.

Aside from those things, my brother in law did admit that he was angry with me too. But didn't step in when I needed him. So we've agreed that this was all just a very bad situation that needs to be ended. So we're just gonna let it rest in peace from here on out.

Lastly, these posts have gotten me a gilfriend. The girl I like had a feeling it was me after she read them, and was just waiting for me to say something. And we'll be going on our first date tonight. So I thank everybody here for their immense support. I really needed it."""

# Apply the function to the input text
output_text = add_gt_in_front_of_paragraphs(input_text)

# Copy the updated text to the clipboard
pyperclip.copy(output_text)

print("The updated text has been copied to the clipboard.")
