rss_feeds = {
    '/dev/lawyer': 'https://writing.kemitchell.com/feed.xml',
    '3 Quarks Daily': 'https://3quarksdaily.com/feed',
    '404 Media': 'https://www.404media.co/rss/',
    'The 19th': 'https://19thnews.org/feed',
    'A Collection of Unmitigated Pedantry': 'https://acoup.blog/feed/',
    'ADDitude: Hyperfocus and ADHD Articles': 'https://www.additudemag.com/tag/hyperfocus/feed/',
    'Afar': 'https://www.afar.com/index.atom',
    'After School': 'https://afterschool.substack.com/feed',
    'The Aftermath': 'https://aftermath.site/feed',
    'Agile &amp; Coding': 'https://davidvujic.blogspot.com/feeds/posts/default?alt=rss',
    'AI Snake Oil': 'https://www.aisnakeoil.com/feed',
    'alexsci- Robert Alexander': 'https://alexsci.com/blog/rss.xml',
    'Alexwlchan': 'https://alexwlchan.net/atom.xml',
    'Ali Barthwell Author Archive': 'https://politepol.com/fd/Z7RsuNu72Zc4.xml',
    'Ali Reza Hayati': 'https://alirezahayati.com/feed/',
    'The Alt Media': 'https://www.thealtmedia.com/feed',
    'Amadeus Maximilian’s Blog': 'https://amxmln.com/rss.xml',
    'Amelia Wattenberger': 'https://wattenberger.com/rss.xml',
    'The American Pamphleteer': 'https://ladylibertie.substack.com/feed',
    'amiantos': 'https://amiantos.net/feed/',
    'Ana Rodrigues': 'https://ohhelloana.blog/feed.xml',
    'Anarcat': 'https://anarc.at/blog/index.rss',
    'Andy Bell': 'https://bell.bz/feed.xml',
    'Anil Dash': 'https://www.anildash.com/feed.xml',
    'Ann Friedman': 'https://us7.campaign-archive.com/feed?u=4a77dae67a768bc3b920d4961&id=e8184bf53a',
    'Antipope': 'http://www.antipope.org/charlie/blog-static/atom.xml',
    'Anya Prosvetova': 'https://www.anyalitica.dev/feed.xml',
    'antirez': 'https://antirez.com/rss',
    'App Defaults': 'https://defaults.rknight.me/feed.xml',
    'AppAddict': 'https://appaddict.app/feed.atom',
    'The Appeal': 'https://theappeal.org/theappeal',
    'Armin Ronacher': 'https://lucumr.pocoo.org/feed.atom',
    'ArtButMakeItSports': 'https://www.artbutmakeitsports.com/feed',
    'A Very Good Blog': 'https://gkeenan.co/avgb/feed.xml',
    'arun.is': 'https://arun.is/rss.xml',
    'Attack of the 50 Foot Blockchain': 'https://davidgerard.co.uk/blockchain/feed/',
    'The Audacity': 'https://audacity.substack.com/feed',
    'The Audacity of Despair': 'https://davidsimon.com/feed/',
    'Austin Henley': 'https://austinhenley.com/blog/feed.rss',
    'Awesome Python Weekly': 'https://python.libhunt.com/newsletter/feed',
    'Awful Announcing': 'https://awfulannouncing.com/feed',
    'The Baffler': 'https://thebaffler.com/homepage/feed',
    'Balkinization': 'https://balkin.blogspot.com/feeds/posts/default',
    'Balls and Strikes': 'https://ballsandstrikes.org/feed/',
    'Bart de Goede': 'https://bart.degoe.de/index.xml',
    'Baseballmusings.com': 'http://feeds2.feedburner.com/Baseballmusingscom',
    'Baty.net': 'https://baty.net/index.xml',
    'The Beacon': 'https://thebeaconnews.org/feed/',
    'The Beautiful Mess': 'https://cutlefish.substack.com/feed',
    'Bellingcat': 'https://www.bellingcat.com/feed/',
    'The Belly of the Beast': 'https://stevenjharper.substack.com/feed',
    'Ben Boyter': 'https://boyter.org/index.xml',
    'Benji.dog': 'https://www.benji.dog/bookmarks.xml',
    'Bicycle For Your Mind': 'https://bicycleforyourmind.com/feed.rss',
    'BIG by Matt Stoller': 'https://www.thebignewsletter.com/feed',
    'Bill McKibben': 'https://billmckibben.substack.com/feed',
    'Birchtree': 'https://birchtree.me/rss/',
    'bitches gotta eat!': 'https://bitchesgottaeat.substack.com/feed',
    'bitecode': 'https://www.bitecode.dev/feed',
    'Bits About Money': 'https://www.bitsaboutmoney.com/archive/rss/',
    'Blackbird Spyplane': 'https://www.blackbirdspyplane.com/feed',
    'Blog of the Day': 'https://blogofthe.day/feed.xml',
    'Blogroll.org': 'https://blogroll.org/feed',
    'The Bored Horse': 'https://bored.horse/feed.xml',
    'Brian Moylan Author Archive': 'https://politepol.com/fd/VoicyDwzX43M.xml',
    'brr- Antarctica': 'https://brr.fyi/feed.xml',
    'Bryan Maniotakis': 'https://bryanmanio.com/feed/',
    'bt': 'https://btxx.org/index.rss',
    'The Bulwark': 'https://thebulwark.com/feed/',
    'but shes a girl...': 'https://www.rousette.org.uk/index.xml',
    'Buzz Machine': 'https://buzzmachine.com/feed/',
    'Cafe Hysteria': 'https://madisonhuizinga.substack.com/feed',
    'Cal Paterson': 'https://calpaterson.com/calpaterson.rss',
    'The Candybox Blog': 'http://www.nathalielawhead.com/candybox/feed',
    'CaptainAwkward.com': 'https://captainawkward.com/feed/',
    'The Cassandra Collective': 'https://cassandracollective.ghost.io/rss/',
    'Cerealously': 'http://www.cerealously.net/feed/',
    'Chefie Data Newsletter': 'https://nouman10.substack.com/feed',
    'Chris Coyier': 'https://chriscoyier.net/feed/',
    'Chris Glass': 'https://chrisglass.com/feed/',
    'Chris Shaw': 'https://thoughts.uncountable.uk/feed',
    'Citation Needed': 'https://www.citationneeded.news/rss/',
    'Civil Discourse with Joyce Vance': 'https://joycevance.substack.com/feed',
    'Clients From Hell': 'https://notalwaysright.com/tag/clients-from-hell/feed/',
    'Club Sportico': 'https://club.sportico.com/feed',
    'Coding Horror- Jeff Atwood': 'https://blog.codinghorror.com/index.xml',
    'colossal': 'https://www.thisiscolossal.com/feed/',
    'Confessions of a Data Guy': 'https://www.confessionsofadataguy.com/feed/',
    'Constantly Hating': 'https://constantlyhating.substack.com/feed',
    'ContraBandCamp': 'https://www.contrabandcamp.com/feed',
    'The Contrarian': 'https://contrarian.substack.com/feed',
    'Cool As Heck': 'https://cool-as-heck.blog/feed/',
    'The Copetti site': 'https://www.copetti.org/index.xml',
    'Corey Robin': 'https://coreyrobin.com/feed',
    'Counting Stuff': 'https://www.counting-stuff.com/rss/',
    'CREW': 'https://www.citizensforethics.org/feed',
    'Crooked Timber': 'https://crookedtimber.org/feed/',
    'CROW’s Substack': 'https://crownewsletter.substack.com/feed',
    'Culture Study- Anne Helen Petersen': 'https://annehelen.substack.com/feed',
    'Current Affairs': 'https://www.currentaffairs.org/news/rss.xml',
    'Curtis McHale': 'https://curtismchale.ca/feed/',
    'Damn Interesting': 'http://www.damninteresting.com/?feed=rss2',
    'Dan Ritz': 'https://www.danritz.com/feed.xml',
    'Dan Sinkers Blog': 'https://dansinker.com/feed.xml',
    'Daniel Lemire': 'https://lemire.me/blog/feed/',
    'Danny Funt+': 'https://dannyfunt.substack.com/feed',
    'Darek Kay': 'https://darekkay.com/atom.xml',
    'Data Engineer Things': 'https://blog.det.life/feed',
    'Data Engineering Central': 'https://dataengineeringcentral.substack.com/feed',
    'daverupert.com': 'https://daverupert.com/atom.xml',
    'David Pape': 'https://www.zyzzyxdonta.net/index.xml',
    'default.blog': 'https://www.counting-stuff.com/rss/',
    'Democracy Docket': 'https://www.democracydocket.com/feed/',
    'Democracy Forward': 'https://democracyforward.org/feed',
    'DepthHub': 'https://www.reddit.com/r/DepthHub/.rss',
    'Design Mom': 'https://designmom.substack.com/feed',
    'The Desolation of Blog- Jeff Johnson': 'https://lapcatsoftware.com/articles/atom.xml',
    'The Digital Antiquarian': 'https://www.filfre.net/feed/rss/',
    'Discourse Blog': 'https://www.discourseblog.com/feed',
    'The Dispatch': 'https://thedispatch.com/feed/',
    'Django Andy': 'https://djangoandy.com/feed/',
    'Dmitry Frank': 'https://dmitryfrank.com/lib/plugins/feed/feed.php?plugin=blog&fn=getBlog&ns=blog&title=Blog',
    'Doc Searls': 'https://doc.searls.com/feed/',
    'Documented': 'https://documentedny.com/feed',
    'Drew deVault': 'https://drewdevault.com/blog/index.xml',
    'Dropsite News': 'https://www.dropsitenews.com/feed?sectionId=136117',
    'The Dry Down': 'https://thedrydown.substack.com/feed/',
    'Dynomight': 'https://dynomight.net/feed.xml',
    'Eater -  Kansas City': 'https://www.eater.com/rss/kansas-city/index.xml',
    'Economics from the Top Down': 'https://economicsfromthetopdown.com/feed/',
    'Ed Zitrons Wheres Your Ed At': 'https://www.wheresyoured.at/feed',
    'Election Law Blog': 'https://electionlawblog.org/?feed=rss2',
    'The Electric Typewriter': 'https://electrictype.substack.com/feed',
    'Ellane W': 'https://ellanew.com/feed.rss',
    'Email is good.': 'https://email-is-good.com/feed/',
    'Ethan Persoff': 'https://www.ep.tc/rss.xml',
    'Evan Miller': 'https://www.evanmiller.org/news.xml',
    'Farm to Fountains': 'https://farmtofountains.com/feed/',
    'fasterthanli.me': 'https://fasterthanli.me/index.xml',
    'FedScoop': 'https://fedscoop.com/feed/',
    'Five Books': 'https://fivebooks.com/feed/',
    'Fix The News': 'https://fixthenews.com/rss/',
    'Flatland KC': 'https://flatlandkc.org/feed/',
    'Flow State': 'https://www.flowstate.fm/feed',
    'The Flytrap': 'https://rss.beehiiv.com/feeds/OmyX5EL51W.xml',
    'Fogknife': 'https://fogknife.com/atom.xml',
    'Fractal Kitty': 'https://www.fractalkitty.com/rss/',
    'Freddie deBoer': 'https://freddiedeboer.substack.com/feed',
    'Friends of Type': 'https://feeds.feedburner.com/FriendsOfType',
    'Futility Closet': 'http://feeds.feedburner.com/FutilityCloset',
    'The Future, Now and Then': 'https://davekarpf.substack.com/feed',
    'Garbage Day': 'https://rss.beehiiv.com/feeds/owMwaGYU36.xml',
    'The Generalist Academy': 'https://generalist.academy/feed/',
    'Gin and Tacos': 'http://www.ginandtacos.com/feed/',
    'GM Games – Sports General Manager Video Games': 'https://gmgames.org/feed/',
    'GOLIKEHELLMACHINE': 'https://golikehellmachine.com/feed/',
    'Good Morning, Hello, How Are You?': 'https://buttondown.com/rickwebb/rss',
    'Gwern.net Newsletter': 'https://gwern.substack.com/feed/',
    'Hackaday': 'https://hackaday.com/feed/',
    'The Handbasket': 'https://rss.beehiiv.com/feeds/40ZQ7CSldT.xml',
    'Hanselman': 'https://www.hanselman.com/blog/feed/rss',
    'Hatewatch- Southern Poverty Law Center': 'https://www.splcenter.org/resources/hate-watch/feed/',
    'Heather Bryant — @HBCompass': 'https://www.hbcompass.io/rss/',
    'Hell Gate': 'https://hellgatenyc.com/all-posts/rss/',
    'Here Fot It- R. Eric Thomas': 'https://letter.rericthomas.com/rss/',
    'Highbrown/Lowbrow': 'https://highbrownlowbrow.substack.com/feed',
    'hjr265.me': 'https://hjr265.me/blog/index.xml',
    'Hopium Chronicles By Simon Rosenberg': 'https://www.hopiumchronicles.com/feed',
    'How Things Work': 'https://www.hamiltonnolan.com/feed',
    'Humane Ingenuity': 'https://newsletter.dancohen.org/rss.xml',
    'I Love Typography': 'https://ilovetypography.com/feed/',
    'i.webthings.hub': 'https://iwebthings.joejenett.com/feed.atom',
    'Indexed': 'http://thisisindexed.com/feed/',
    'inessential': 'https://inessential.com/feed.json',
    'Indieseek': 'https://indieseek.xyz/feed/',
    'Ineza Bonté': 'https://www.ineza.codes/rss.xml',
    'Infinite Wishes': 'https://emmas.site/blog/atom.xml',
    'Interconnected': 'https://interconnected.org/home/feed',
    'International Consortium of Investigative Journalists': 'https://www.icij.org/feed',
    'Into The Fountains': 'https://intothefountains.substack.com/feed',
    'Its FOSS': 'https://itsfoss.com/feed/',
    'Jack H. Peterson': 'https://jackhpeterson.com/atom.xml',
    'James Coffee Blog': 'https://jamesg.blog/feeds/posts.xml',
    'Jim Nielsen': 'https://blog.jim-nielsen.com/feed.xml',
    'Joe Ross': 'https://joeross.me/feed.xml',
    'John D. Cook': 'https://www.johndcook.com/blog/feed',
    'Julia Evans': 'https://jvns.ca/atom.xml',
    'jwz': 'https://cdn.jwz.org/blog/feed/',
    'Kalzumeus': 'https://www.kalzumeus.com/feed/articles/',
    'Kansas City Royals – MLB Trade Rumors': 'https://www.mlbtraderumors.com/kansas-city-royals/feed/atom',
    'Kansas Reflector': 'https://kansasreflector.com/feed/',
    'Katherine Yang': 'https://kayserifserif.place/feed.xml',
    'KCUR- Local Food ': 'https://www.kcur.org/tags/local-food.rss',
    'Ken Shirriff': 'https://www.righto.com/feeds/posts/default',
    'Kendra Little': 'https://kendralittle.com/blog/rss.xml',
    'kenpoms thoughts': 'https://kenpom.substack.com/feed/',
    'Kev Quirk': 'https://kevquirk.com/feed',
    'Kicks Condor': 'https://www.kickscondor.com/feed.xml',
    'kk.org': 'https://kk.org/feed',
    'kottke.org': 'http://feeds.kottke.org/main',
    'krrd.ing': 'https://krrd.ing/rss.xml',
    'Lambda Legal': 'https://lambdalegal.org/feed/',
    'The Land of Random': 'https://thelandofrandom.substack.com/feed',
    'Laura Olin': 'https://buttondown.com/lauraolin/rss',
    'Law Dork': 'https://www.lawdork.com/feed',
    'Lazybear': 'https://lazybea.rs/index.xml',
    'Legal Profession Blog': 'http://feeds.feedburner.com/LegalProfessionBlog',
    'Liberal Currents': 'https://www.liberalcurrents.com/rss/',
    'Live Laugh Blog': 'https://livelaugh.blog/rss.xml',
    'Longreads': 'https://longreads.com/feed/',
    'LostFocus': 'https://lostfocus.de/feed/',
    'Lowering the Bar': 'http://feeds.feedblitz.com/loweringthebar&x=1',
    'Lucian Truscott Newsletter': 'https://luciantruscott.substack.com/feed',
    'Luke Muehlhauser': 'http://lukemuehlhauser.com/feed/',
    'Maggie Appleton': 'https://maggieappleton.com/rss.xml',
    'MANU': 'https://manuelmoreale.com/feed/rss',
    'Manton Reece': 'https://www.manton.org/feed.xml',
    'Math & Programming': 'https://www.jeremykun.com/index.xml',
    'The Markup': 'https://themarkup.org/feeds/rss.xml',
    'Martin Fowler': 'https://martinfowler.com/feed.atom',
    'Mathspp': 'https://mathspp.com/blog.atom',
    'Matt Bruenig Dot Com': 'https://mattbruenig.com/feed/',
    'Matthew Lyon': 'https://lyonhe.art/index.xml',
    'mattrighetti': 'https://mattrighetti.com/feed.xml',
    'maya.land': 'https://maya.land/feed.xml',
    'McFilter': 'http://www.mcqn.net/mcfilter/index.xml',
    'Media Matters for America': 'https://politepol.com/fd/TZerYpPaBA2M',
    'Meditations In An Emergency': 'https://www.meditationsinanemergency.com/rss/',
    'Michael Sippey': 'https://sippey.com/rss.xml',
    'Michael Tsai': 'https://mjtsai.com/blog/feed/',
    'Molly Whites activity feed': 'https://www.mollywhite.net/feed/feed.xml',
    'The Moral High Ground': 'https://evanhurst.substack.com/feed',
    'Mouse vs. Python': 'https://www.blog.pythonlibrary.org/feed/',
    'Nabeel Valley': 'https://nabeelvalley.co.za/feed/rss.xml',
    'Narratively': 'https://narratively.com/feed/',
    'The Nation- Electoral Reform': 'https://www.thenation.com/feed/?post_type=article&subject=electoral-reform',
    'The Nation- Supreme Court': 'https://www.thenation.com/feed/?post_type=article&subject=supreme-court',
    'Ned Batchelder': 'http://nedbatchelder.com/blog/rss.xml',
    'Neil’s Substack': 'https://neilpaine.substack.com/feed',
    'Neilzone': 'https://neilzone.co.uk/index.xml',
    'Nerd Reich': "https://www.thenerdreich.com/rss/",
    'Never Hungover': 'https://www.neverhungover.club/feed',
    'Nicola Iarocci': 'https://nicolaiarocci.com/index.xml',
    'Nieman Lab': 'https://www.niemanlab.org/feed/',
    'ni.har': 'https://nih.ar/rss.xml',
    'Noahpinion': 'https://www.noahpinion.blog/feed',
    'Not Always Legal': 'https://notalwaysright.com/legal/feed/',
    'Not Always Right- Inspirational': 'https://notalwaysright.com/tag/inspirational/feed/',
    'Notes by JCProbably': 'https://notes.jeddacp.com/feed/',
    'Notes on the Crises- Nathan Tankus': 'https://www.crisesnotes.com/rss/',
    'notnite': 'https://notnite.com/blog/rss.xml',
    'NPR: Food': 'https://feeds.npr.org/1053/rss.xml',
    'null program- Chris Wellons': 'https://nullprogram.com/feed/',
    'The Old Curmudgeon- Jon Margolis': 'https://jonmargolis.substack.com/feed',
    'Old Vintage Computing Research': 'https://oldvcr.blogspot.com/feeds/posts/default',
    'Omar Rizwan': 'https://omar.website/posts/index.xml',
    'One First- Steve Vladeck': 'https://www.stevevladeck.com/feed',
    'One Foot Tsunami': 'https://onefoottsunami.com/feed/atom/',
    'One Point Zero': 'https://onepointzero.com/feed/basic',
    'ongoing by Tim Bray': 'http://www.tbray.org/ongoing/ongoing.atom',
    'ooh directory- Tech': 'https://ooh.directory/feeds/cats/b7q2w7/rss/technology.xml',
    'Ordinary Times': 'https://ordinary-times.com/feed/',
    'Original Jurisdiction- David Lat': 'https://davidlat.substack.com/feed',
    'Own Your Web': 'https://buttondown.email/ownyourweb/rss',
    'Paradox': 'https://www.paradoxnewsletter.com/feed',
    'Patrick Van der Spiegels Posts': 'https://patrick.vanderspie.gl/posts/index.xml',
    'Paul Gross': 'https://www.pgrs.net/feed.xml',
    'Paul Kinlan': 'https://paul.kinlan.me/index.xml',
    'Paul Krugman': 'https://paulkrugman.substack.com/feed',
    'Perl Hacks': 'https://perlhacks.com/feed/',
    'The Perry Bible Fellowship': 'https://pbfcomics.com/feed/',
    'Personal sites are awesome': 'https://personalsit.es/feed/all.xml',
    'The Pitch': 'https://www.thepitchkc.com/category/news-52777/feed/',
    'Pitch Weekly': 'https://www.thepitchkc.com/feed/',
    'Pitch Weekly: Food & Drink': 'https://www.thepitchkc.com/category/food-drink/feed/',
    'Pixel Envy': 'https://feedpress.me/pxlnv',
    'Planet Python': 'https://planetpython.org/rss20.xml',
    'plover': 'https://blog.plover.com/index.rss',
    'Popular Information': 'https://popular.info/feed',
    'Power 3.0 | Authoritarian Resurgence, Democratic Resilience': 'https://www.power3point0.org/feed/podcast/',
    'The Power Rank': 'https://thepowerrank.com/feed/',
    'Poynter': 'https://www.poynter.org/feed/',
    'Prism Politics and Democracy': 'https://prismreports.org/category/politics-democracy/feed/',
    'Process Things - Code': 'https://exch.gr/code/feed.xml',
    'Process Things - Essays': 'https://exch.gr/essays/feed.xml',
    'ProHoopsHistory Newsletter': 'https://prohoopshistory.substack.com/feed',
    'ProPublica': 'http://feeds.propublica.org/propublica/main',
    'Prospect361': 'https://prospect361.com/feed',
    'Public Citizen': 'https://www.citizen.org/feed/',
    'Public Notice': 'https://www.publicnotice.co/feed',
    'Pudding.cool': 'https://pudding.cool/feed.xml',
    'PyBites': 'https://pybit.es/feed/',
    'PyCoders Weekly': 'https://pycoders.com/feed/T8SjZAIK',
    'PyMOTW on Doug Hellmann': 'https://feeds.feedburner.com/PyMOTW',
    'Python In Office': 'https://pythoninoffice.com/feed/',
    'Python Insider': 'https://blog.python.org/feeds/posts/default',
    'Python Morsels': 'https://www.pythonmorsels.com/topics/feed/',
    'The Python Papers': 'https://www.pythonpapers.com/feed',
    'The Python Rabbithole': 'https://zlliu.substack.com/feed',
    'Python Weekly': 'http://us2.campaign-archive1.com/feed?u=e2e180baf855ac797ef407fc7&id=9e26887fc5',
    'Qubyte Codes': 'https://qubyte.codes/social.atom.xml',
    'Quotaliciousness': 'https://quotulatiousness.ca/blog/feed/',
    'The Racket News': 'https://www.theracketnews.com/feed',
    'The Watch- Radley Balko': 'https://radleybalko.substack.com/feed',
    'Raymond Camden': 'https://www.raymondcamden.com/feed.xml',
    'Read Rodge': 'https://rodgersherman.substack.com/feed',
    'read-only': 'https://read-only.net/feed.xml',
    'Recomendo': 'https://www.recomendo.com/feed',
    'ReedyBears Blog': 'https://reedybear.bearblog.dev/feed/',
    'Reilly Spitzfaden': 'https://reillyspitzfaden.com/blog/feed.xml',
    'Renga In Blue': 'https://bluerenga.blog/feed/',
    'Rest of World - Digital utopia': 'https://restofworld.org/feed/collection/digital-utopia',
    'Rest of World - The future of work': 'https://restofworld.org/feed/collection/future-of-work',
    'The Righting': 'https://www.therighting.com/feed',
    'Roads & Kingdoms': 'https://roadsandkingdoms.com/feed/',
    'Robin Rendle': 'https://buttondown.com/robinrendle/rss',
    'Robin Sloan': 'https://www.robinsloan.com/feed.xml',
    'The Root': 'https://www.theroot.com/rss',
    'Rosemary Orchard |': 'https://rosemaryorchard.com/feed.xml',
    'RotoGraphs Fantasy Baseball': 'https://fantasy.fangraphs.com/feed/',
    'Royals Farm Report': 'https://royalsfarmreport.com/feed/',
    'Royals Review -  All Posts': 'https://www.royalsreview.com/rss/index.xml',
    'Royals – FanGraphs Baseball': 'https://www.fangraphs.com/blogs/category/teams/royals/feed/',
    'Rubenerd': 'http://showfeed.rubenerd.com/',
    'Salon.com > amanda_marcotte': 'https://www.salon.com/writer/amanda_marcotte/feed',
    'Sandwich Tribunal': 'https://www.sandwichtribunal.com/feed/',
    'Scott Aaronson': 'https://scottaaronson.blog/?feed=rss2',
    'Screenshot Reliquary': 'https://screenshotreliquary.substack.com/feed',
    'Scriveners Error': 'https://scrivenerserror.blogspot.com/feeds/posts/default?alt=rss',
    'seize the dev': 'https://akr.am/blog/feed.xml',
    'Sergis writing': 'https://sergiswriting.com/atom.xml',
    'Shatter Zone': 'https://shatterzone.substack.com/feed',
    'Shellsharks Feeds': 'https://shellsharks.com/feeds/feed.xml',
    'Simone': 'https://simone.org/rss/',
    'Sludge': 'https://readsludge.com/feed/',
    'The Small Bow': 'https://www.thesmallbow.com/feed',
    'small good things': 'https://eilloh.net/posts_feed',
    'The Smart Set': 'https://www.thesmartset.com/feed/',
    'splitbrain.org - blog': 'https://www.splitbrain.org/feed/blog',
    'SportsLogos.Net News': 'https://news.sportslogos.net/feed/',
    'SQL Shack – articles about database auditing, server performance, data recovery, and more': 'https://www.sqlshack.com/feed/',
    'Standard Ebooks - New Releases': 'https://standardebooks.org/rss/new-releases',
    'Statistical Modeling, Causal Inference, and Social Science': 'https://statmodeling.stat.columbia.edu/feed/',
    'The Status Kuo': 'https://statuskuo.substack.com/feed',
    'Steven A. Guccione': 'https://stevesaltfacebook.blog/feed/',
    'Strength in Numbers': 'https://www.gelliottmorris.com/feed',
    'The Sunday Long Read': 'https://us9.campaign-archive.com/feed?id=67e6e8a504&u=6e1ae4ac632498a38c1d57c54',
    'The Sword And the Sandwich': 'https://buttondown.com/theswordandthesandwich/rss',
    'Tales of Whoa': 'http://brownforsheriff.tumblr.com/rss',
    'Talking Points Memo': 'https://talkingpointsmemo.com/feed',
    'The Tao of Mac': 'https://taoofmac.com/atom.xml',
    'Tastefully Offensive': 'https://www.tastefullyoffensive.com/feed/',
    'Tech Support': 'https://techsupport.substack.com/feed',
    'Teen Vogue': 'https://politepol.com/fd/Vjc601sG0jpO.xml',
    'Terence Eden’s Blog': 'https://shkspr.mobi/blog/feed/atom/',
    'Texas Monthly': 'https://www.texasmonthly.com/feed',
    'Thinking about...- Timothy Snyder': 'https://snyder.substack.com/feed',
    'Tommy Craggs': 'https://tommycraggs.com/feed/',
    'Tracy Durnell': 'https://tracydurnell.com/feed/',
    'Trades Ten Years Later': 'https://tradestenyearslater.substack.com/feed',
    'Trout Nation': 'http://jennytrout.com/?feed=rss2',
    'Troy Vassalotti :: Blog': 'https://www.troyv.dev/feed.xml',
    'Twitter @Rany Jazayerli': 'https://rsshub.app/twitter/user/jazayerli/exclude_rts_replies=1&forceWebApi=1',
    'UnHerd': 'https://unherd.com/feed/',
    'Unnamed Website': 'https://unnamed.website/index.xml',
    'URL Media': 'https://url-media.com/feed/',
    'The Useless Web': 'https://theuselessweb.com/sites/index.xml',
    'User Mag': 'https://www.usermag.co/feed',
    'Uses This': 'https://usesthis.com/feed.atom',
    'Vaporwave Van Gogh': 'https://vaporwave-van-gogh.tumblr.com/rss',
    'The Verge Installer Newsletter': 'https://www.theverge.com/rss/installer-newsletter/index.xml',
    'Veronica Writes': 'https://berglyd.net/feed.xml',
    'Vicki Boykis': 'https://vickiboykis.com/index.xml',
    'victory journal': 'https://victoryjournal.com/feed',
    'VZQK50': 'https://www.vzqk50.com/blog/scraps//../../index.xml',
    'Weekend Reading- Michael Podhorzer': 'https://www.weekendreading.net/feed',
    'Welcome To Hell World': 'https://www.welcometohellworld.com/rss/',
    'Werd I/O': 'https://granary.io/url?url=https://werd.io/content/all/&input=html&output=atom&hub=https://bridgy-fed.superfeedr.com/',
    'what are the haps': 'https://ryannorth.tumblr.com/rss',
    'Whatever': 'https://whatever.scalzi.com/feed/',
    'Whats Good at Trader Joes': 'http://www.whatsgoodattraderjoes.com/feeds/posts/default',
    'The Whimsical Web': 'https://whimsical.club/feed.xml',
    'Why Evolution Is True': 'https://whyevolutionistrue.com/feed/',
    'Why Is This Interesting?': 'https://whyisthisinteresting.substack.com/feed',
    'wilw.dev': 'https://wilw.dev/rss.xml',
    'Will Lockett': 'https://www.planetearthandbeyond.co/feed',
    'Window Seat- Stuart Loh': 'https://stuloh.substack.com/feed',
    'Wonder Tools': 'https://wondertools.substack.com/feed',
    'Wonkette': 'http://wonkette.com/feed',
    'Worrydream': 'https://worrydream.com/feed.xml',
    'Wrong Hands': 'https://wronghands1.com/feed/',
    'x-log': 'https://blog.x-way.org/atom.xml',
    'xandra.cc': 'https://library.xandra.cc/feed/?type=rss',
    'Xe Iaso': 'https://xeiaso.net/blog.rss',
    'ℤ→ℤ': 'https://ztoz.blog/index.xml',
    'Zserge': 'https://zserge.com/rss.xml',
    'Indieblog': ' 	https://indieblog.page/rss',
    'The Public Domain': 'https://www.thepublicdomain.org/feed/',
    'The Waiting Room': 'https://ameliatait.substack.com/feed',
    'The Sling': 'https://www.thesling.org/feed',
    'Lawfare- Courts & Litigation': 'https://www.lawfaremedia.org/feeds/courts-litigation',
    'Lawfare- Congress': 'https://www.lawfaremedia.org/feeds/congress',
    'Lawfare- Democracy & Elections': 'https://www.lawfaremedia.org/feeds/democracy-elections',
    'Lawfare- Executive Branch': 'https://www.lawfaremedia.org/feeds/executive-branch',
    'Asterisk Mag': 'https://asteriskmag.com/feed',
    'Zeldman': 'https://zeldman.com/feed/',
}

# Function to remove "The " from the start of a title for sorting purposes
def sort_key(title):
    title = title.lower()
    if title.startswith("the "):
        title = title[4:]
    return title

# Sort the rss_feeds dictionary by keys without paying attention to capitalization
sorted_rss_feeds = dict(sorted(rss_feeds.items(), key=lambda item: sort_key(item[0])))

# Write the sorted dictionary to a file
output_file = "/Users/muneer78/Downloads/sorted_rss_feeds.txt"
with open(output_file, 'w') as file:
    file.write("rss_feeds = {\n")
    for key, value in sorted_rss_feeds.items():
        file.write(f"    '{key}': '{value}',\n")
    file.write("}\n")

print(f"Sorted RSS feeds have been written to {output_file}")